### PR TITLE
Add TypeScript support and update dependencies 

### PR DESCRIPTION
**Pull request by petetnt**
This PR adds TypeScript support and updates the dependencies fixing #62 on the way

My chosen tactic for this is to have the normal eslint to lint `js` and `jsx` files, while letting `typescript-eslint` handle the `ts` and `tsx` files. Alternative would be letting `typescript-eslint` handle everything and adding `ecmaFeatures.jsx` to `true` to the `parserOptions`

This is published as `eslint-config-motley@12.0.0-alpha.5` so feel free to test it with 

```
npx install-peerdeps --dev eslint-config-motley@12.0.0-alpha.6
```

### CODE REVIEW

**Comment by petetnt** [comment]
https://github.com/motleyagency/eslint-config-motley/pull/64/commits/c6a7b3198443c1eec72501e592942237fbbceb07 published as `12.0.0-alpha.6`

**Comment by valstu** [comment]
Had a bit of problems with this when I tried it during the weekend. It didn't install the eslint.config file when using it with latest cra version 🤔

**Comment by valstu** [comment]
Something weird is going on. Running the `npx install-peerdeps --dev eslint-config-motley@12.0.0-alpha.6` asks if I want to use yarn to install these, if I click yes or no, no matter what it doesn't do anything. I was now finally able to get it running by removing the yarn.lock file first and then running the same command. 🤔

**Comment by valstu** [comment]
Ok, got it working by running 
```bash
npx install-peerdeps --dev eslint-config-motley@12.0.0-alpha.6 --yarn
```

**Comment by valstu** [comment]
Added some minor updates, seems to work quite nice. Tested out the optional chaining with latest create-react-app version.

**Comment by valstu** [comment]
New version released:
Try it with `npx install-peerdeps --dev eslint-config-motley@12.0.0-alpha.7`

**Comment by petetnt** [comment]
@turansadri reported that the `JS` linting fails if `typescript` is not installed because `@typescript-eslint` fails. I thought the plugins were only loaded for overrides if they were used but apparently not.

Should be have a `--typescript` flag?

**Comment by valstu** [comment]
I just noticed the same

**Comment by valstu** [comment]
We shouldn't probably install the peerdeps that are used with typescript then. But I'm not sure how to make that conditional 🤔 `install-peerdeps` will always install all the peer deps in package.json. I wouldn't like to separate these to a different repos either 🤔

**Comment by petetnt** [comment]
Let's split it into two packages

**Comment by petetnt** [comment]
Now it seems to work, at least the TypeScript version.

Can you check @valstu 

```
npx install-peerdeps --dev eslint-config-motley@12.0.0-alpha.14 --yarn if using Yarn.

```

**Pull request merged**
